name: 'build and push to ghcr'

on: push

env:
  IMAGE_NAME: 'kafka-to-gps-connector'
  REGISTRY: 'ghcr.io'

jobs:
  lower-case-owner:
    runs-on: ubuntu-latest
    steps:
      - name: LowerCase repo owner
        run: |
          echo "REPO_OWNER_LC=${GITHUB_REPOSITORY_OWNER,,}" >> ${GITHUB_ENV}

  get-gitversion:
    runs-on: ubuntu-latest
    needs: [lower-case-owner]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.10
        with:
          versionSpec: '5.x'

      - name: Execute GitVersion
        uses: gittools/actions/gitversion/execute@v0.9.10
        with:
          useConfigFile: false

      - name: 'Set version in ${GITHUB_ENV}'
        run: |
          echo "GITVERSION_SEMVER_LC=${GITVERSION_SEMVER}" >> ${GITHUB_ENV}

  build-n-push:
    runs-on: ubuntu-latest
    if: endsWith(github.ref, '/master')
    needs: [get-gitversion]
    env:
      GITVERSION_SEMVER: ${{ github.GITVERSION_SEMVER_LC }}
      REPO_OWNER: ${{ github.REPO_OWNER_LC }}
    container:
      image: docker:stable
    # defaults:
    #   run:
    #     # Force sh since bash is not supported in docker:stable
    #     shell: sh
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Login ghcr.io
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Display SemVer
        run: |
          echo "SemVer: ${{ env.GITVERSION_SEMVER }}"

      - name: Build and push to registry
        run: |
          docker build -t ${{ env.REGISTRY }}/${{ env.REPO_OWNER }}/${{ env.IMAGE_NAME }}:${{ env.GITVERSION_SEMVER }} \
                       -t ${{ env.REGISTRY }}/${{ env.REPO_OWNER }}/${{ env.IMAGE_NAME }}:latest .
          docker push -a ${{ env.REGISTRY }}/${{ env.REPO_OWNER }}/${{ env.IMAGE_NAME }}
